rollout:
  replicas: 2
  strategy:
    blueGreen:
      activeService: simple-web-active
      previewService: simple-web-preview
      autoPromotionEnabled: false

image:
  repository: nginx
  tag: "1.21"
  pullPolicy: IfNotPresent

service:
  port: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi