apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-web-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Shrinidhikulkarni7/argocd-example
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-web-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true