apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: rollout-es
  namespace: simple-web-prod
spec:
  template:
    serviceAccountName: argo-events-sa
  resource:
    rollout-preview:
      interval: 10s
      group: argoproj.io
      version: v1alpha1
      resource: rollouts
      namespace: simple-web-prod
      filter:
        fields:
          - key: metadata.name
            value: simple-web-prod
          - key: status.blueGreen.previewService
            type: string
            operation: exists