apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-events-sa
  namespace: simple-web-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-events-role
  namespace: simple-web-prod
rules:
  - apiGroups: ["argoproj.io"]
    resources: ["workflows", "workflowtemplates", "rollouts"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-events-rolebinding
  namespace: simple-web-prod
subjects:
  - kind: ServiceAccount
    name: argo-events-sa
roleRef:
  kind: Role
  name: argo-events-role
  apiGroup: rbac.authorization.k8s.io