apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication
spec:
  selector:
    matchLabels:
      app: myapplication
  replicas: 2
  template:
    metadata:
      labels:
        app: myapplication
    spec:
      containers:
        - name: myapplication
          image: nanajanashia/argocd-app:1.3
          ports:
            - containerPort: 8080